### ISSUE TITLE
Error when build project

### ISSUE THREAD

**Issue by murillocg** [murillocg/goleador#13]
When building, it's ocurring following error:

```
[ERROR]  11% building modules 11/17 modules 6 active ...fonts\fontawesome-webfont.ttf?v=4.7.0Template parse warnings:
[ERROR] The <template> element is deprecated. Use <ng-template> instead ("
[ERROR]   <div class="card">
[ERROR]     [WARNING ->]<template ngFor let-panel [ngForOf]="panels">
[ERROR]       <div role="tab" id="{{panel.id}}-header"
[ERROR]         "): ng:///C:/projetos/goleador/src/main/webapp/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.NgbAccordion.html@2:4
```

**Comment by pedrorohr** [comment]
It's because we are using ng-bootstrap with Angular 4. <template> was deprecated on the last version of Angular.
The ng-bootstrap team is [working on it](https://github.com/ng-bootstrap/ng-bootstrap/issues/1337).

When they release the new version, we just need to run `npm install ng-bootstrap@latest` on webapp folder.

**Comment by murillocg** [comment]
Ok. So, Let's wait.
